### ISSUE TITLE
无法获取 "椒盐音乐" 的歌词

### ISSUE THREAD

**Issue by xzx482** [xiaowine/Lyrics-Getter#31]
我不确定这个问题是椒盐音乐的问题还是这个模块的问题,但是在使用时,这个模块抛异常了
可能这个异常就是不能显示歌词的线索

其他音乐软件(酷狗概念版)使用正常

设备及系统信息 Redmi 23054RA19C, Android 13, MIUI14

root管理器为 KernelSU
xp框架为 LSPosed 1.8.6 (6712) - Zygisk

其他xp模块为 "墨-状态栏歌词" "异常追踪"

模块版本为2.0.1
椒盐音乐版本为8.14.3

触发异常步骤
    1.打开模块
    2.切换到"App规则"
    3.切换到"主页",点击"重启作用域软件"
    4.再次切换到"App规则"
    5.使用系统导航键或手势回到系统桌面(不是按返回)
    6.异常已引发,在LSPosed日志中可查看

<details><summary>异常日志</summary><pre><code>

java.lang.IllegalArgumentException: Parcel: unknown type for value AppInfos(appName=椒盐音乐, appIcon=android.graphics.drawable.AdaptiveIconDrawable@bbca08f, packageName=com.salt.music, versionCode=2023082701, appRule=AppRule(packageName=com.salt.music, name=椒盐音乐, rules=[Rule(useApi=true, apiVersion=4, startVersionCode=2023071601, endVersionCode=2023081000, excludeVersions=[], getLyricType=0, remarks=), Rule(useApi=true, apiVersion=5, startVersionCode=2023081001, endVersionCode=2147483647, excludeVersions=[], getLyricType=0, remarks=)]), installed=true)
	at android.os.Parcel.getValueType(Parcel.java:2409)
	at android.os.Parcel.writeValue(Parcel.java:2308)
	at android.os.Parcel.writeList(Parcel.java:1382)
	at android.os.Parcel.writeValue(Parcel.java:2460)
	at android.os.Parcel.writeValue(Parcel.java:2316)
	at android.os.Parcel.writeList(Parcel.java:1382)
	at android.os.Parcel.writeValue(Parcel.java:2460)
	at android.os.Parcel.writeValue(Parcel.java:2316)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1265)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1802)
	at android.os.Bundle.writeToParcel(Bundle.java:1362)
	at android.os.Parcel.writeBundle(Parcel.java:1334)
	at android.os.Parcel.writeValue(Parcel.java:2433)
	at android.os.Parcel.writeValue(Parcel.java:2323)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1265)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1802)
	at android.os.Bundle.writeToParcel(Bundle.java:1362)
	at android.os.Parcel.writeBundle(Parcel.java:1334)
	at android.os.Parcel.writeValue(Parcel.java:2433)
	at android.os.Parcel.writeValue(Parcel.java:2323)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1265)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1802)
	at android.os.Bundle.writeToParcel(Bundle.java:1362)
	at android.os.Parcel.writeBundle(Parcel.java:1334)
	at android.os.Parcel.writeValue(Parcel.java:2433)
	at android.os.Parcel.writeValue(Parcel.java:2323)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1265)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1802)
	at android.os.Bundle.writeToParcel(Bundle.java:1362)
	at android.os.Parcel.writeBundle(Parcel.java:1334)
	at android.os.Parcel.writeValue(Parcel.java:2433)
	at android.os.Parcel.writeValue(Parcel.java:2323)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1265)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1802)
	at android.os.Bundle.writeToParcel(Bundle.java:1362)
	at android.os.Parcel.writeBundle(Parcel.java:1334)
	at android.os.Parcel.writeValue(Parcel.java:2433)
	at android.os.Parcel.writeValue(Parcel.java:2323)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1265)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1802)
	at android.os.Bundle.writeToParcel(Bundle.java:1362)
	at android.os.Parcel.writeBundle(Parcel.java:1334)
	at android.os.Parcel.writeValue(Parcel.java:2433)
	at android.os.Parcel.writeValue(Parcel.java:2323)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1265)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1802)
	at android.os.Bundle.writeToParcel(Bundle.java:1362)
	at android.os.Parcel.writeBundle(Parcel.java:1334)
	at android.os.Parcel.writeValue(Parcel.java:2433)
	at android.os.Parcel.writeValue(Parcel.java:2323)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1265)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1802)
	at android.os.Bundle.writeToParcel(Bundle.java:1362)
	at android.os.Parcel.writeBundle(Parcel.java:1334)
	at android.os.Parcel.writeValue(Parcel.java:2433)
	at android.os.Parcel.writeValue(Parcel.java:2323)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1265)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1802)
	at android.os.Bundle.writeToParcel(Bundle.java:1362)
	at android.os.Parcel.writeBundle(Parcel.java:1334)
	at android.os.Parcel.writeValue(Parcel.java:2433)
	at android.os.Parcel.writeValue(Parcel.java:2323)
	at android.os.BaseBundle.dumpStats(BaseBundle.java:1874)
	at android.os.BaseBundle.dumpStats(BaseBundle.java:1911)
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:150)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8315)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)

</code></pre></details>

**Comment by xiaowine** [comment]
ui上的报错并不会影响hook

**Comment by xiaowine** [comment]
![Screenshot_2023-08-28-12-46-05-784_com.salt.music.jpg](https://github.com/xiaowine/Lyric-Getter/assets/68009112/9a9f8ea2-0261-49dd-96b3-e365890ebfc5)

**Comment by xzx482** [comment]
抱歉打扰到你了，是椒盐音乐的问题，我去酷安下了8.14.1的旧版就可以用的了(github上没有这个版本,害得我换了一大堆版本)。8.14.3的更新日志还说修复了歌词问题,我才怀疑是这个模块的问题，结果还是它的问题。不过这个UI的问题还是有的,也修修吧

**Comment by xiaowine** [comment]
> 抱歉打扰到你了，是椒盐音乐的问题，我去酷安下了8.14.1的旧版就可以用的了(github上没有这个版本,害得我换了一大堆版本)。8.14.3的更新日志还说修复了歌词问题,我才怀疑是这个模块的问题，结果还是它的问题。不过这个UI的问题还是有的,也修修吧

实测是修复了

**Comment by xzx482** [comment]
我这里还是不行的，可能哪里还有BUG吧，只有8.14.1能显示歌词

https://github.com/xiaowine/Lyric-Getter/assets/46856523/cc5f669a-9160-4e4b-a171-51a7c8df2f46
