### ISSUE TITLE
2.0.5抓不到新版网易云歌词

### ISSUE THREAD

**Issue by WakiJi** [xiaowine/Lyrics-Getter#60]
状态栏歌词（6.0.2）和墨丶息（4.0.21695201527868）都没法显示歌词
网易云音乐版本8.10.61
lsp抓到lyric getter输出报错如下

[ 2023-10-16T08:56:55.461    10276: 30453: 30938 E/LSPosed-Bridge  ] kotlin.UninitializedPropertyAccessException: lateinit property sharedPreferences has not been initialized
	at cn.xiaowine.dsp.DSP.getSharedPreferences(DSP.kt:15)
	at cn.xiaowine.dsp.delegate.SerialLazyDelegate.getValue(SerialLazyDelegate.kt:19)
	at cn.lyric.getter.config.Config.getRegexReplace(Config.kt:12)
	at cn.lyric.getter.tool.EventTools$special$$inlined$observableChange$1.afterChange(Tool.kt:232)
	at kotlin.properties.ObservableProperty.setValue(ObservableProperty.kt:41)
	at cn.lyric.getter.tool.EventTools.setLastLyricData(EventTools.kt:17)
	at cn.lyric.getter.tool.EventTools.sendLyric(EventTools.kt:58)
	at cn.lyric.getter.tool.EventTools.sendLyric(EventTools.kt:36)
	at cn.lyric.getter.hook.app.Netease$init$1$1$1$1$1.invoke$lambda$0(Netease.kt:48)
	at cn.lyric.getter.hook.app.Netease$init$1$1$1$1$1.$r8$lambda$qmWx3oBmWHD1exy0DafyDc4Mz0s(Unknown Source:0)
	at cn.lyric.getter.hook.app.Netease$init$1$1$1$1$1$$ExternalSyntheticLambda0.onMethodHooked(Unknown Source:2)
	at com.github.kyuubiran.ezxhelper.HookFactory$create$1.afterHookedMethod(HookFactory.kt:77)
	at VjnpL.EnIdb.JRBqn.BVUg.XposedBridge$LegacyApiSupport.handleAfter(Unknown Source:33)
	at J.callback(Unknown Source:292)
	at LSPHooker_.i(Unknown Source:8)
	at al1.g.e0(ProGuard:24)
	at al1.g.Q(ProGuard:1)
	at al1.g$g.e(ProGuard:5)
	at al1.g$g.d(ProGuard:26)
	at al1.g$g.handleMessage(ProGuard:190)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by xiaowine** [comment]
请尝试使用ci
